services:
  mysql:
    image: mysql:8.0
    container_name: to_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-travel_order_dev}
      MYSQL_USER: ${MYSQL_USER:-to_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-to_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  gotenberg:
    image: thecodingmachine/gotenberg:8
    container_name: gotenberg
    restart: unless-stopped
    ports:
      - "4000:3000" # host port 4000 â†’ container port 3000
    volumes:
      - gotenberg-data:/gotenberg

volumes:
  mysql-data:
  gotenberg-data: